### ISSUE TITLE
Provide text data for leaflets, or a drawing file for local reproduction

### ISSUE THREAD

**Issue by omgitsgela** [gravitystorm/openstreetmap-promotional-leaflets#3]
I'd like to print these at home for myself and friends. The text data isn't present in the repository. Can you provide that?

**Comment by gravitystorm** [comment]
The text data is in the SVGs (but the github SVG preview doesn't show it). Can you try opening the SVGs with a tool like Inkscape and see if you can see the text?

**Comment by gravitystorm** [comment]
Ah, I see that this has also been covered in the comments to Alex's diary post - https://www.openstreetmap.org/user/alexkemp/diary/47345 . Do get in touch if there's anything else that I can help with.
